name: ame_yame
version: 0.1.0
description: ame_yame bot
author: sh4869 <nobuk4869@gmail.com>
homepage: https://github.com/sh4869/ame_yame
dependencies:
  http: ">=0.11.1+1 <0.12.0"
  oauth: ">=0.3.0 <0.4.0"
  

